### ISSUE TITLE
cpl cn master weburl page source request

### ISSUE THREAD

**Issue by ipstreet312** [BG47510/sniftv#1]
Bonjour @BG47510 merci pour votre projet, je suis tombé sur :
https://github.com/BG47510/sniftv/blob/main/cpl/cn.m3u8
J'aurais voulu savoir si vous savez le site ou page web url d'obtention de ce contenu de master svp ?
Le lien du master est : https://hls-m013.p-cdnlive-edge020311-dual.scy.canalplus-cdn.net/__token__id%3D1a569a48e47690c700c0f71662c87679~hmac%3D6d2114baa9bb694f530073a9f707530612577a89d4d0a36aaa72374fa9e12049/live/disk/cnews-clair-hd/hls-v3-hd-clair/cnews-clair-hd.m3u8
Merci bien ! cdlt

**Comment by BG47510** [comment]
Bonsoir @ipstreet312  je profite de votre message pour vous féliciter sur la qualité de votre projet.
Cdt.
