### ISSUE TITLE
absolute path

### ISSUE THREAD

**Issue by campones** [BG47510/sniftv#2]
hello

I was wondering if the path  to the raw  content could be different
for instance, instead to be

path/to/bouy/fx.m3u8 

would be 

/path/to/bouy/fx/index.m3u8
or
/path/to/bouy/fx/playlist.m3u8

also, I was asking myself how much time the  m3u8 works. you need to update them very frequently?

cheers

**Comment by BG47510** [comment]
Hello
This is possible, but it requires having one directory per path.

M3u8 are updated every 3 hours

Best regards see you soon

**Comment by campones** [comment]
yes, exactly,  aka one directory per  channel
