### ISSUE TITLE
 france.tv HD 

### ISSUE THREAD

**Issue by 3052** [BG47510/sniftv#3]
can you get HD with france.tv? I think the current code returns SD:

https://github.com/BG47510/sniftv/blob/main/py/frtvn.py

**Comment by BG47510** [comment]
the code return
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:LANGUAGE="fra",AUTOSELECT=YES,CHANNELS="2",FORCED=NO,TYPE=AUDIO,URI="https://live-ssai.ftven.fr/ZXhwPTE3MTIxNjE3OTF+YWNsPSUyZip+aG1hYz1jN2RjMzllNDVjMDdhYWViN2ZhM2NiZjBjMTg3MzgwZWYzODJkZTlkNmI4OTkyNjg0MjNlNWI3ZGFkZTg1ZTY5/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/f85095e7-f5e1-4569-8419-66825db73764/6.m3u8",GROUP-ID="audio_0",DEFAULT=YES,NAME="1 Francais"
#EXT-X-MEDIA:LANGUAGE="qad",AUTOSELECT=NO,CHANNELS="2",FORCED=NO,TYPE=AUDIO,URI="https://live-ssai.ftven.fr/ZXhwPTE3MTIxNjE3OTF+YWNsPSUyZip+aG1hYz1jN2RjMzllNDVjMDdhYWViN2ZhM2NiZjBjMTg3MzgwZWYzODJkZTlkNmI4OTkyNjg0MjNlNWI3ZGFkZTg1ZTY5/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/f85095e7-f5e1-4569-8419-66825db73764/7.m3u8",GROUP-ID="audio_0",DEFAULT=NO,NAME="2 Audio Description"
#EXT-X-MEDIA:LANGUAGE="qaa",AUTOSELECT=NO,CHANNELS="2",FORCED=NO,TYPE=AUDIO,URI="https://live-ssai.ftven.fr/ZXhwPTE3MTIxNjE3OTF+YWNsPSUyZip+aG1hYz1jN2RjMzllNDVjMDdhYWViN2ZhM2NiZjBjMTg3MzgwZWYzODJkZTlkNmI4OTkyNjg0MjNlNWI3ZGFkZTg1ZTY5/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/f85095e7-f5e1-4569-8419-66825db73764/8.m3u8",GROUP-ID="audio_0",DEFAULT=NO,NAME="3 Version Originale"
#EXT-X-MEDIA:LANGUAGE="fre",AUTOSELECT=YES,FORCED=NO,TYPE=SUBTITLES,URI="https://live-ssai.ftven.fr/ZXhwPTE3MTIxNjE3OTF+YWNsPSUyZip+aG1hYz1jN2RjMzllNDVjMDdhYWViN2ZhM2NiZjBjMTg3MzgwZWYzODJkZTlkNmI4OTkyNjg0MjNlNWI3ZGFkZTg1ZTY5/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/f85095e7-f5e1-4569-8419-66825db73764/9.m3u8",GROUP-ID="subtitles",DEFAULT=YES,NAME="Francais"
#EXT-X-STREAM-INF:CODECS="avc1.42C01E,mp4a.40.2",AVERAGE-BANDWIDTH=236914,RESOLUTION=256x144,SUBTITLES="subtitles",FRAME-RATE=25.0,BANDWIDTH=343600,AUDIO="audio_0"
https://live-ssai.ftven.fr/ZXhwPTE3MTIxNjE3OTF+YWNsPSUyZip+aG1hYz1jN2RjMzllNDVjMDdhYWViN2ZhM2NiZjBjMTg3MzgwZWYzODJkZTlkNmI4OTkyNjg0MjNlNWI3ZGFkZTg1ZTY5/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/f85095e7-f5e1-4569-8419-66825db73764/0.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.42C01E,mp4a.40.2",AVERAGE-BANDWIDTH=547167,RESOLUTION=384x216,SUBTITLES="subtitles",FRAME-RATE=25.0,BANDWIDTH=672452,AUDIO="audio_0"
https://live-ssai.ftven.fr/ZXhwPTE3MTIxNjE3OTF+YWNsPSUyZip+aG1hYz1jN2RjMzllNDVjMDdhYWViN2ZhM2NiZjBjMTg3MzgwZWYzODJkZTlkNmI4OTkyNjg0MjNlNWI3ZGFkZTg1ZTY5/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/f85095e7-f5e1-4569-8419-66825db73764/1.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.4D401E,mp4a.40.2",AVERAGE-BANDWIDTH=1152114,RESOLUTION=640x360,SUBTITLES="subtitles",FRAME-RATE=25.0,BANDWIDTH=1313712,AUDIO="audio_0"
https://live-ssai.ftven.fr/ZXhwPTE3MTIxNjE3OTF+YWNsPSUyZip+aG1hYz1jN2RjMzllNDVjMDdhYWViN2ZhM2NiZjBjMTg3MzgwZWYzODJkZTlkNmI4OTkyNjg0MjNlNWI3ZGFkZTg1ZTY5/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/f85095e7-f5e1-4569-8419-66825db73764/2.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.4D401F,mp4a.40.2",AVERAGE-BANDWIDTH=1647167,RESOLUTION=960x540,SUBTITLES="subtitles",FRAME-RATE=25.0,BANDWIDTH=1867729,AUDIO="audio_0"
https://live-ssai.ftven.fr/ZXhwPTE3MTIxNjE3OTF+YWNsPSUyZip+aG1hYz1jN2RjMzllNDVjMDdhYWViN2ZhM2NiZjBjMTg3MzgwZWYzODJkZTlkNmI4OTkyNjg0MjNlNWI3ZGFkZTg1ZTY5/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/f85095e7-f5e1-4569-8419-66825db73764/3.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.64001F,mp4a.40.2",AVERAGE-BANDWIDTH=2857132,RESOLUTION=1280x720,SUBTITLES="subtitles",FRAME-RATE=25.0,BANDWIDTH=3267844,AUDIO="audio_0"
https://live-ssai.ftven.fr/ZXhwPTE3MTIxNjE3OTF+YWNsPSUyZip+aG1hYz1jN2RjMzllNDVjMDdhYWViN2ZhM2NiZjBjMTg3MzgwZWYzODJkZTlkNmI4OTkyNjg0MjNlNWI3ZGFkZTg1ZTY5/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/f85095e7-f5e1-4569-8419-66825db73764/4.m3u8
#EXT-X-STREAM-INF:CODECS="avc1.640029,mp4a.40.2",AVERAGE-BANDWIDTH=5717132,RESOLUTION=1920x1080,SUBTITLES="subtitles",FRAME-RATE=25.0,BANDWIDTH=6069703,AUDIO="audio_0"
https://live-ssai.ftven.fr/ZXhwPTE3MTIxNjE3OTF+YWNsPSUyZip+aG1hYz1jN2RjMzllNDVjMDdhYWViN2ZhM2NiZjBjMTg3MzgwZWYzODJkZTlkNmI4OTkyNjg0MjNlNWI3ZGFkZTg1ZTY5/dai/v1/manifest/14bff07f70f2518f32f1c6cc13a91ef489dc83f1/SSARFrance2OTTEMTConfiguration/f85095e7-f5e1-4569-8419-66825db73764/5.m3u8

**Comment by 3052** [comment]
not for this one
https://www.france.tv/films/6002616-wall-street.html

**Comment by BG47510** [comment]
module to handle live streaming.
